spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:postgresql://localhost:5432/inventoryDB
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql



server:
  servlet:
    context-path: /api/v1
  port: 9010