spring:
  application:
    name: inventory-service

#DB config
  datasource:
    url: jdbc:postgresql://localhost:5432/inventoryDB
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#SQL file config
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql


#server config
server:
  servlet:
    context-path: /inventory
  port: 9010

#eureka config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka